/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns the panel's health status. Anonymous (no Bearer
         *     required); used by the load balancer and the CI smoke test.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate
         * @description Exchange username + password for an access token and a refresh
         *     token. Wrong credentials always return 401 — the error never
         *     distinguishes "unknown user" from "wrong password" so
         *     attackers cannot enumerate.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Malformed body or missing fields */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Trade a refresh token for a fresh access+refresh pair. The
         *     presented token is consumed (single-use). Reuse of a
         *     consumed token is detected and triggers chain revocation:
         *     every outstanding refresh for the user is invalidated,
         *     the response is 401, and a `WARN` log line is emitted. This
         *     is the most likely signal of token theft.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Malformed body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /**
                 * @description Invalid or already-used refresh token; chain may have
                 *     been revoked.
                 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who am I
         * @description Return the identity of the principal behind the bearer
         *     access token.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MeResponse"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Internal error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Core provider catalog
         * @description Returns the list of registered sing-box / Xray / Hysteria 2
         *     provider names plus the in-development (noop) dev provider
         *     when the panel is in `AEGIS_ENV != production`. The UI uses
         *     this to render the "core provider" badge on the Nodes page.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoreListResponse"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List nodes
         * @description Every VPN node registered with the panel. The list is sorted
         *     by `name` ascending. v0.1.0 does not paginate — the panel
         *     scale is "tens of nodes" so the full list is fine.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NodeListResponse"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Register a node
         * @description Register a new VPN node with the panel. The agent
         *     registration handshake is a separate step that lands with
         *     the BYO Node flow in v0.3 (per the v9 §3.3 roadmap); for now
         *     the panel stores the node metadata and the operator SSHes
         *     into the node by hand to install the agent.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NodeCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Name or address already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a node */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * Update a node
         * @description Partial update (the same PUT semantics the rest of the
         *     v0.2.0 CRUD surfaces use). Absent keys mean "leave alone".
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NodeUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Node"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a node */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}/inbounds": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
            };
            cookie?: never;
        };
        /**
         * List inbounds for a node
         * @description Every inbound registered on the given node. The list is
         *     sorted by `name` ascending. v0.1.0 does not paginate.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InboundListResponse"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Register an inbound
         * @description Create a new protocol listener on the given node. The
         *     `params` field is a free-form JSON blob whose schema is
         *     owned by the sing-box provider; v0.2.0 surfaces a generic
         *     JSON editor for it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InboundCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inbound"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Name or port already in use on this node */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{nodeId}/inbounds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: string;
                id: string;
            };
            cookie?: never;
        };
        /** Get an inbound */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inbound"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Update an inbound */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InboundUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Inbound"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Delete an inbound */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    nodeId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List hosts
         * @description Every host (bundle of endpoints) registered with the panel.
         *     v0.1.0 does not paginate.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HostListResponse"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a host
         * @description Create a new host. The `endpoints` array is required
         *     (cross-field validation: 1 endpoint for `type=direct`,
         *     2+ endpoints plus a balancer strategy for `type=balancer`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HostCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Host"];
                    };
                };
                /** @description Validation error (including cross-field) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hosts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a host */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Host"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Update a host */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HostUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Host"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a host */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Every end-user VPN account registered with the panel.
         *     v0.1.0 does not paginate.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListResponse"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a user
         * @description Create a new end-user account. The server generates a
         *     fresh `sub_token` (32 hex chars) and returns it in the
         *     response — the operator hands the token to the user out-
         *     of-band (e.g. via the admin UI's "show once" dialog).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Username already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Get a user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Partial update (the same PATCH semantics the v0.2 CRUD
         *     surfaces use). Use the `sub_token` PATCH to rotate the
         *     sub_token; use the `status: deleted` PATCH to soft-delete
         *     the user. The dedicated `POST /users/{id}/rotate-token`
         *     endpoint is a convenience for the rotation case.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/users/{id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the user's sub_token
         * @description Generate a fresh sub_token. The previous token stops
         *     working immediately (no grace window) — the operator
         *     hands the new token to the user out-of-band and the user
         *     re-imports the URL on every device.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panelcfg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the active sub_path
         * @description Returns the current URL prefix for the subscription
         *     endpoint. An empty string means the documented
         *     `/api/v1/sub/{token}` path is in use (the default).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PanelPathConfig"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panelcfg/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate to a fresh random sub_path */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PanelPathConfig"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panelcfg/rotate-to": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate to an explicit sub_path */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PanelPathRotateToRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PanelPathConfig"];
                    };
                };
                /** @description Invalid path (length or charset) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/panelcfg/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset to the default empty sub_path */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PanelPathConfig"];
                    };
                };
                /** @description Missing or invalid bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sub/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        /**
         * Render a subscription
         * @description The public subscription render endpoint. The
         *     `{token}` is the user's `sub_token` (the credential).
         *     The `?target=` query parameter selects the wire
         *     format (`base64` default, `singbox`, `clash`, `html`).
         *     The endpoint is rate-limited per sub_token (1 rps
         *     sustained, 5 burst by default); an over-budget
         *     request returns 429 with a `Retry-After` header.
         */
        get: {
            parameters: {
                query?: {
                    target?: "base64" | "singbox" | "clash" | "html";
                };
                header?: never;
                path: {
                    token: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /** @example vless://uuid@node1.example.com:443?type=tcp&security=none#node1 */
                        "text/plain": string;
                        /**
                         * @example {
                         *       "outbounds": [
                         *         {
                         *           "type": "vless",
                         *           "server": "node1.example.com",
                         *           "port": 443
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": {
                            [key: string]: unknown;
                        };
                        /**
                         * @example proxies:
                         *       - name: "node1"
                         *         type: vless
                         *         server: node1.example.com
                         *         port: 443
                         */
                        "text/yaml": string;
                        /**
                         * @example <!doctype html>
                         *     <html><body><h1>AegisPanel subscription</h1></body></html>
                         */
                        "text/html": string;
                    };
                };
                /** @description Missing sub_token */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description User is not in a live state (disabled / expired / deleted) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unknown sub_token */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unsupported ?target= value */
                415: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /**
                 * @description Rate limit exceeded. The `Retry-After` header
                 *     contains the wall-clock seconds to wait before
                 *     retrying.
                 */
                429: {
                    headers: {
                        "Retry-After"?: number;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Human-readable error message. For security reasons
             *     the auth endpoints collapse several failure modes
             *     into a single generic message; do not branch on
             *     the message text.
             */
            error: string;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** @example 0.0.0-dev */
            version: string;
            /** @example deadbeef */
            commit?: string;
        };
        CoreListResponse: {
            providers: components["schemas"]["CoreProvider"][];
        };
        CoreProvider: {
            /** @example singbox */
            name: string;
            /** @example 1.8.0 */
            version: string;
            /** @description True when this is a development-only provider (e.g. noop). */
            dev?: boolean;
        };
        LoginRequest: {
            /** @example admin */
            username: string;
            /**
             * Format: password
             * @example aegis-dev-password
             */
            password: string;
        };
        RefreshRequest: {
            /**
             * @description Opaque 32-byte hex token (64 chars lowercase). Only the
             *     SHA-256 hash is stored server-side.
             * @example 4f2a8b...64hex
             */
            refresh_token: string;
        };
        LoginResponse: {
            /** @description HS256 JWT access token. 15-min TTL. */
            access_token: string;
            /**
             * @description Opaque refresh token. 30-day TTL. Single-use; rotation
             *     on every refresh.
             */
            refresh_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** Format: date-time */
            expires_at: string;
            scopes: ("admin" | "read" | "write" | "nodes" | "users" | "subscriptions" | "hosts")[];
        };
        MeResponse: {
            /** @example u-bootstrap */
            user_id: string;
            /** @example admin */
            username: string;
            scopes: ("admin" | "read" | "write" | "nodes" | "users" | "subscriptions" | "hosts")[];
        };
        /** @enum {string} */
        NodeState: "new" | "online" | "draining" | "offline" | "disabled";
        Node: {
            /** Format: uuid */
            id: string;
            name: string;
            region: string;
            state: components["schemas"]["NodeState"];
            /** @description SSH endpoint (host:port) the panel uses to reach the node. */
            address: string;
            capacityHint?: string;
            tags?: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NodeCreateRequest: {
            name: string;
            region: string;
            address: string;
            capacityHint?: string;
        };
        NodeUpdateRequest: {
            name?: string;
            region?: string;
            address?: string;
            state?: components["schemas"]["NodeState"];
            capacityHint?: string;
            tags?: string[];
        };
        NodeListResponse: {
            nodes: components["schemas"]["Node"][];
        };
        /** @enum {string} */
        Protocol: "vless" | "hysteria2" | "shadowsocks" | "trojan";
        Inbound: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            nodeId: string;
            name: string;
            protocol: components["schemas"]["Protocol"];
            /** @example :: */
            listen: string;
            listenPort: number;
            listenPorts?: number[];
            enabled: boolean;
            tags?: string[];
            /**
             * @description Protocol-specific configuration. The shape is owned
             *     by the sing-box provider; v0.2.0 surfaces a generic
             *     JSON editor for it.
             */
            params?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        InboundCreateRequest: {
            name: string;
            protocol: components["schemas"]["Protocol"];
            listen?: string;
            listenPort: number;
            listenPorts?: number[];
            enabled?: boolean;
            tags?: string[];
            params?: {
                [key: string]: unknown;
            };
        };
        InboundUpdateRequest: {
            name?: string;
            protocol?: components["schemas"]["Protocol"];
            listen?: string;
            listenPort?: number;
            listenPorts?: number[];
            enabled?: boolean;
            tags?: string[];
            params?: {
                [key: string]: unknown;
            };
        };
        InboundListResponse: {
            inbounds: components["schemas"]["Inbound"][];
        };
        /** @enum {string} */
        HostType: "direct" | "balancer";
        /** @enum {string} */
        BalancerStrategy: "round_robin" | "least_loaded" | "random" | "least_ping" | "urltest";
        Balancer: {
            strategy: components["schemas"]["BalancerStrategy"];
            /** Format: uri */
            healthcheckUrl?: string;
            healthcheckIntervalSec?: number;
            failoverEndpointIds?: string[];
        };
        Endpoint: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            nodeId: string;
            /** Format: uuid */
            inboundId: string;
            /** @default 1 */
            weight: number;
            address?: string[];
            port?: number;
            sni?: string[];
            host?: string[];
            path?: string;
            /** Format: uuid */
            downloadHostId?: string;
        };
        Host: {
            /** Format: uuid */
            id: string;
            remark: string;
            displayName?: string;
            type: components["schemas"]["HostType"];
            enabled: boolean;
            priority: number;
            statusFilter?: ("active" | "on_hold" | "expired" | "limited" | "disabled")[];
            /** @description ISO 3166-1 alpha-2 country code. */
            country?: string;
            city?: string;
            tags?: string[];
            endpoints: components["schemas"]["Endpoint"][];
            balancer?: components["schemas"]["Balancer"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        HostCreateRequest: {
            remark: string;
            displayName?: string;
            type: components["schemas"]["HostType"];
            enabled?: boolean;
            priority?: number;
            statusFilter?: ("active" | "on_hold" | "expired" | "limited" | "disabled")[];
            country?: string;
            city?: string;
            tags?: string[];
            endpoints: components["schemas"]["Endpoint"][];
            balancer?: components["schemas"]["Balancer"];
        };
        HostUpdateRequest: {
            remark?: string;
            displayName?: string;
            type?: components["schemas"]["HostType"];
            enabled?: boolean;
            priority?: number;
            statusFilter?: ("active" | "on_hold" | "expired" | "limited" | "disabled")[];
            country?: string;
            city?: string;
            tags?: string[];
            endpoints?: components["schemas"]["Endpoint"][];
            balancer?: components["schemas"]["Balancer"];
        };
        HostListResponse: {
            hosts: components["schemas"]["Host"][];
        };
        /** @enum {string} */
        UserLifecycleStatus: "active" | "grace" | "disabled" | "expired" | "deleted";
        User: {
            /** Format: uuid */
            id: string;
            username: string;
            status: components["schemas"]["UserLifecycleStatus"];
            /** Format: uuid */
            planId?: string;
            /** Format: date-time */
            expireAt?: string;
            /** Format: int64 */
            trafficLimitBytes: number;
            /** Format: int64 */
            trafficUsedBytes: number;
            deviceLimit: number;
            hostsAllowlist?: string[];
            hostsBlocklist?: string[];
            subToken: string;
            /** Format: date-time */
            subTokenRotatedAt?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserCreateRequest: {
            username: string;
            status?: components["schemas"]["UserLifecycleStatus"];
            /** Format: uuid */
            planId?: string;
            /** Format: date-time */
            expireAt?: string;
            /** Format: int64 */
            trafficLimitBytes?: number;
            deviceLimit?: number;
        };
        UserUpdateRequest: {
            username?: string;
            status?: components["schemas"]["UserLifecycleStatus"];
            /** Format: uuid */
            planId?: string;
            clearPlanId?: boolean;
            /** Format: date-time */
            expireAt?: string;
            clearExpireAt?: boolean;
            /** Format: int64 */
            trafficLimitBytes?: number;
            deviceLimit?: number;
        };
        UserListResponse: {
            users: components["schemas"]["User"][];
        };
        PanelPathConfig: {
            /** Format: uuid */
            id: string;
            /**
             * @description The current URL prefix. Empty = the default
             *     `/api/v1/sub/{token}` path. Non-empty = a rotated
             *     secret prefix.
             */
            subPath: string;
            /** Format: date-time */
            rotatedAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        PanelPathRotateRequest: {
            /**
             * @description Grace window during which the OLD sub_path is
             *     still served. 0 = no grace. The server caps at
             *     1 hour.
             */
            graceWindowSeconds?: number;
        };
        PanelPathRotateToRequest: {
            /** @description The new sub_path. Must match [a-z0-9-]{4,64}. */
            subPath: string;
            graceWindowSeconds?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
