// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Aegis panel <-> node control plane (gRPC).
//
// This file is the canonical wire definition. The generated stubs land in
// `backend/internal/agentv1pb/` and are imported by both the panel binary
// (`github.com/QAdversif/AegisPanel/backend/cmd/aegis`) and the per-node
// agent binary (`github.com/QAdversif/AegisPanel/backend/cmd/aegis-agent`).
//
// # Versioning
//
// Package `aegis.v1` is the v0.8.29+ wire. The HTTP+bearer path stays
// live until v0.8.32 (cut release, see
// `docs/superpowers/plans/2026-08-25-mtls-grpc-agent.md`). Pre-1.0
// breaking changes are allowed in `v1` because the panel and the
// agent are version-locked at install time (the agent reads
// `AEGIS_AGENT_PANEL_VERSION` at boot and refuses to start if the
// panel is older than the agent's expected minimum).
//
// Post-1.0 (out of scope here), breaking changes land in `aegis.v2`
// and `v1` is supported for 1 release.
//
// # Why gRPC, not HTTP/2 + JSON
//
// The v0.4.0-b HTTP+bearer surface uses hand-rolled JSON encoders
// that escape non-BMP runes as 5-hex-digit `"\u1F680"` instead of a
// surrogate pair (closed in v0.8.28.6 #300, but the bug class is
// permanently gated by switching to protobuf). gRPC also gives us:
//   - mTLS without an extra reverse proxy
//   - Generated stubs in any language (operator-side tooling)
//   - `google.golang.org/grpc/status` for typed errors (replaces the
//     v0.8.7 401 -> `nodes.Service.RefreshAgentBearer` retry path
//     with `code = Unauthenticated` -> retry-once)
//
// # Auth (v0.8.30+)
//
// v0.8.29 ships without mTLS. The agent validates the same bearer
// secret it uses on the HTTP path (read from `AEGIS_AGENT_BEARER`,
// surfaced via gRPC metadata `authorization: Bearer <token>`) so the
// sanity smoke in v0.8.29 catches wire bugs before cert provisioning
// lands in v0.8.30. v0.8.30 replaces the bearer with mTLS; the
// bearer path is removed in v0.8.32.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: aegis/v1/agent.proto

package aegisv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AegisAgent_Apply_FullMethodName  = "/aegis.v1.AegisAgent/Apply"
	AegisAgent_Status_FullMethodName = "/aegis.v1.AegisAgent/Status"
	AegisAgent_Stats_FullMethodName  = "/aegis.v1.AegisAgent/Stats"
	AegisAgent_Health_FullMethodName = "/aegis.v1.AegisAgent/Health"
)

// AegisAgentClient is the client API for AegisAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AegisAgent is the panel-to-node control plane. The methods mirror
// the v0.4.0-b HTTP surface 1:1 so the v0.8.29 dual-stack transport
// switch in `internal/agentgrpc` can pick the same underlying side
// effects regardless of transport.
//
// Each method takes a `*Request` / `*Response` pair even when the
// request body is empty (e.g. `HealthRequest`). This keeps
// `google.api.http` annotations available post-1.0 without a
// breaking wire change.
type AegisAgentClient interface {
	// Apply pushes a rendered sing-box config to the node. The agent
	// writes the bytes to `AEGIS_AGENT_SINGBOX_CONFIG_PATH` (default
	// `/etc/sing-box/config.json`) atomically and then runs
	// `AEGIS_AGENT_SINGBOX_RELOAD_CMD` (default
	// `systemctl reload sing-box`). The same side-effect order as
	// `cmd/aegis-agent/apply.go` L48-58.
	//
	// Errors:
	//   - `INVALID_ARGUMENT` — `config` is empty or larger than
	//     `AEGIS_AGENT_APPLY_MAX_BYTES` (default 1 MiB).
	//   - `INTERNAL` — atomic write failed or reload command exited
	//     non-zero. The reload stderr is in the `google.rpc.Status.message`.
	//   - `UNAUTHENTICATED` (v0.8.29 only) — bearer mismatch. The panel
	//     retries once via `nodes.Service.RefreshAgentBearer`, then
	//     surfaces the error. v0.8.30+ replaces this with mTLS.
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
	// Status returns the node's running state. Mirrors `GET /v1/status`
	// on the HTTP surface.
	//
	// `state` is a free-form string today (`online` / `offline` /
	// `draining` / `disabled` / `new`) because the agent's view of
	// "state" is a copy of the panel's `nodes.state` column, not the
	// source of truth. v1.0.0 will promote it to an enum.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Stats returns per-user traffic counters when the agent has them
	// populated. Empty until the sing-box clash-api integration lands
	// (ARCHITECTURE.md §7.5). The panel tolerates an empty map.
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
	// Health is the liveness probe. Always reachable, even when the
	// bearer is unset (the v0.4.0-b `insecure mode` for first-boot
	// smoke). v0.8.30+ adds a separate unauthenticated `/healthz` HTTP
	// path that dials into this RPC.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type aegisAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAegisAgentClient(cc grpc.ClientConnInterface) AegisAgentClient {
	return &aegisAgentClient{cc}
}

func (c *aegisAgentClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, AegisAgent_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisAgentClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AegisAgent_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisAgentClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, AegisAgent_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aegisAgentClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AegisAgent_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AegisAgentServer is the server API for AegisAgent service.
// All implementations must embed UnimplementedAegisAgentServer
// for forward compatibility.
//
// AegisAgent is the panel-to-node control plane. The methods mirror
// the v0.4.0-b HTTP surface 1:1 so the v0.8.29 dual-stack transport
// switch in `internal/agentgrpc` can pick the same underlying side
// effects regardless of transport.
//
// Each method takes a `*Request` / `*Response` pair even when the
// request body is empty (e.g. `HealthRequest`). This keeps
// `google.api.http` annotations available post-1.0 without a
// breaking wire change.
type AegisAgentServer interface {
	// Apply pushes a rendered sing-box config to the node. The agent
	// writes the bytes to `AEGIS_AGENT_SINGBOX_CONFIG_PATH` (default
	// `/etc/sing-box/config.json`) atomically and then runs
	// `AEGIS_AGENT_SINGBOX_RELOAD_CMD` (default
	// `systemctl reload sing-box`). The same side-effect order as
	// `cmd/aegis-agent/apply.go` L48-58.
	//
	// Errors:
	//   - `INVALID_ARGUMENT` — `config` is empty or larger than
	//     `AEGIS_AGENT_APPLY_MAX_BYTES` (default 1 MiB).
	//   - `INTERNAL` — atomic write failed or reload command exited
	//     non-zero. The reload stderr is in the `google.rpc.Status.message`.
	//   - `UNAUTHENTICATED` (v0.8.29 only) — bearer mismatch. The panel
	//     retries once via `nodes.Service.RefreshAgentBearer`, then
	//     surfaces the error. v0.8.30+ replaces this with mTLS.
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
	// Status returns the node's running state. Mirrors `GET /v1/status`
	// on the HTTP surface.
	//
	// `state` is a free-form string today (`online` / `offline` /
	// `draining` / `disabled` / `new`) because the agent's view of
	// "state" is a copy of the panel's `nodes.state` column, not the
	// source of truth. v1.0.0 will promote it to an enum.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Stats returns per-user traffic counters when the agent has them
	// populated. Empty until the sing-box clash-api integration lands
	// (ARCHITECTURE.md §7.5). The panel tolerates an empty map.
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	// Health is the liveness probe. Always reachable, even when the
	// bearer is unset (the v0.4.0-b `insecure mode` for first-boot
	// smoke). v0.8.30+ adds a separate unauthenticated `/healthz` HTTP
	// path that dials into this RPC.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedAegisAgentServer()
}

// UnimplementedAegisAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAegisAgentServer struct{}

func (UnimplementedAegisAgentServer) Apply(context.Context, *ApplyRequest) (*ApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedAegisAgentServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedAegisAgentServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedAegisAgentServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAegisAgentServer) mustEmbedUnimplementedAegisAgentServer() {}
func (UnimplementedAegisAgentServer) testEmbeddedByValue()                    {}

// UnsafeAegisAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AegisAgentServer will
// result in compilation errors.
type UnsafeAegisAgentServer interface {
	mustEmbedUnimplementedAegisAgentServer()
}

func RegisterAegisAgentServer(s grpc.ServiceRegistrar, srv AegisAgentServer) {
	// If the following call panics, it indicates UnimplementedAegisAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AegisAgent_ServiceDesc, srv)
}

func _AegisAgent_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisAgentServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisAgent_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisAgentServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisAgent_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisAgentServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisAgent_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisAgentServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisAgent_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisAgentServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisAgent_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisAgentServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AegisAgent_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AegisAgentServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AegisAgent_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AegisAgentServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AegisAgent_ServiceDesc is the grpc.ServiceDesc for AegisAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AegisAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aegis.v1.AegisAgent",
	HandlerType: (*AegisAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _AegisAgent_Apply_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _AegisAgent_Status_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _AegisAgent_Stats_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AegisAgent_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aegis/v1/agent.proto",
}
