// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Aegis panel <-> node control plane (gRPC).
//
// This file is the canonical wire definition. The generated stubs land in
// `backend/internal/agentv1pb/` and are imported by both the panel binary
// (`github.com/QAdversif/AegisPanel/backend/cmd/aegis`) and the per-node
// agent binary (`github.com/QAdversif/AegisPanel/backend/cmd/aegis-agent`).
//
// # Versioning
//
// Package `aegis.v1` is the v0.8.29+ wire. The HTTP+bearer path stays
// live until v0.8.32 (cut release, see
// `docs/superpowers/plans/2026-08-25-mtls-grpc-agent.md`). Pre-1.0
// breaking changes are allowed in `v1` because the panel and the
// agent are version-locked at install time (the agent reads
// `AEGIS_AGENT_PANEL_VERSION` at boot and refuses to start if the
// panel is older than the agent's expected minimum).
//
// Post-1.0 (out of scope here), breaking changes land in `aegis.v2`
// and `v1` is supported for 1 release.
//
// # Why gRPC, not HTTP/2 + JSON
//
// The v0.4.0-b HTTP+bearer surface uses hand-rolled JSON encoders
// that escape non-BMP runes as 5-hex-digit `"\u1F680"` instead of a
// surrogate pair (closed in v0.8.28.6 #300, but the bug class is
// permanently gated by switching to protobuf). gRPC also gives us:
//   - mTLS without an extra reverse proxy
//   - Generated stubs in any language (operator-side tooling)
//   - `google.golang.org/grpc/status` for typed errors (replaces the
//     v0.8.7 401 -> `nodes.Service.RefreshAgentBearer` retry path
//     with `code = Unauthenticated` -> retry-once)
//
// # Auth (v0.8.30+)
//
// v0.8.29 ships without mTLS. The agent validates the same bearer
// secret it uses on the HTTP path (read from `AEGIS_AGENT_BEARER`,
// surfaced via gRPC metadata `authorization: Bearer <token>`) so the
// sanity smoke in v0.8.29 catches wire bugs before cert provisioning
// lands in v0.8.30. v0.8.30 replaces the bearer with mTLS; the
// bearer path is removed in v0.8.32.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: aegis/v1/agent.proto

package aegisv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApplyRequest is the panel's "write this and reload" payload.
type ApplyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full rendered sing-box config (raw bytes). The agent does
	// not parse it; the side-effect path is `os.WriteFile + exec`.
	Config        []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_aegis_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

// ApplyResponse is the agent's "wrote it and reloaded" ack.
type ApplyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// `reloaded` is true when the reload command exited 0. When false,
	// the new config is on disk but sing-box is running the old one;
	// the panel surfaces this as a BatchedApplier retry candidate.
	Reloaded bool `protobuf:"varint,1,opt,name=reloaded,proto3" json:"reloaded,omitempty"`
	// Wall-clock cost of the reload command, in milliseconds.
	ReloadDurationMs int64 `protobuf:"varint,2,opt,name=reload_duration_ms,json=reloadDurationMs,proto3" json:"reload_duration_ms,omitempty"`
	// The sing-box version that accepted the config (parsed from
	// `sing-box version` output, or empty if sing-box is not on PATH).
	// v0.8.29 returns empty; v0.8.30+ populates this.
	SingboxVersion string `protobuf:"bytes,3,opt,name=singbox_version,json=singboxVersion,proto3" json:"singbox_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_aegis_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyResponse) GetReloaded() bool {
	if x != nil {
		return x.Reloaded
	}
	return false
}

func (x *ApplyResponse) GetReloadDurationMs() int64 {
	if x != nil {
		return x.ReloadDurationMs
	}
	return 0
}

func (x *ApplyResponse) GetSingboxVersion() string {
	if x != nil {
		return x.SingboxVersion
	}
	return ""
}

// StatusRequest is intentionally empty.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_aegis_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{2}
}

// StatusResponse is a snapshot of the node's runtime.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node state (see service comment).
	State string `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	// The agent's own version (from `AEGIS_AGENT_VERSION`, set at
	// `go build` time via `-ldflags "-X main.version=..."`).
	AgentVersion string `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// The sing-box version, if discoverable. Empty when the agent
	// cannot shell out to `sing-box version` (e.g. before the
	// install_singbox role has run).
	SingboxVersion string `protobuf:"bytes,3,opt,name=singbox_version,json=singboxVersion,proto3" json:"singbox_version,omitempty"`
	// Uptime in seconds since the agent process started.
	UptimeSeconds int64 `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_aegis_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *StatusResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *StatusResponse) GetSingboxVersion() string {
	if x != nil {
		return x.SingboxVersion
	}
	return ""
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// StatsRequest is intentionally empty.
type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_aegis_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{4}
}

// StatsResponse is per-user traffic since the last agent restart.
// The map is keyed by user UUID string. Empty when sing-box's
// clash-api is not yet wired (v0.4.0-c scope).
type StatsResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	UserStats     map[string]*UserTrafficStats `protobuf:"bytes,1,rep,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_aegis_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StatsResponse) GetUserStats() map[string]*UserTrafficStats {
	if x != nil {
		return x.UserStats
	}
	return nil
}

// UserTrafficStats is a per-user byte counter pair.
type UserTrafficStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadBytes   int64                  `protobuf:"varint,1,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes int64                  `protobuf:"varint,2,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTrafficStats) Reset() {
	*x = UserTrafficStats{}
	mi := &file_aegis_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTrafficStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTrafficStats) ProtoMessage() {}

func (x *UserTrafficStats) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTrafficStats.ProtoReflect.Descriptor instead.
func (*UserTrafficStats) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UserTrafficStats) GetUploadBytes() int64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *UserTrafficStats) GetDownloadBytes() int64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

// HealthRequest is intentionally empty.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_aegis_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{7}
}

// HealthResponse is the agent's liveness answer.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uptime in seconds since the agent process started.
	UptimeSeconds int64 `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// The agent's own version. Same source as
	// `StatusResponse.agent_version`.
	AgentVersion  string `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_aegis_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aegis_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_aegis_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

var File_aegis_v1_agent_proto protoreflect.FileDescriptor

const file_aegis_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14aegis/v1/agent.proto\x12\baegis.v1\"&\n" +
	"\fApplyRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\"\x82\x01\n" +
	"\rApplyResponse\x12\x1a\n" +
	"\breloaded\x18\x01 \x01(\bR\breloaded\x12,\n" +
	"\x12reload_duration_ms\x18\x02 \x01(\x03R\x10reloadDurationMs\x12'\n" +
	"\x0fsingbox_version\x18\x03 \x01(\tR\x0esingboxVersion\"\x0f\n" +
	"\rStatusRequest\"\x9b\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion\x12'\n" +
	"\x0fsingbox_version\x18\x03 \x01(\tR\x0esingboxVersion\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\"\x0e\n" +
	"\fStatsRequest\"\xb0\x01\n" +
	"\rStatsResponse\x12E\n" +
	"\n" +
	"user_stats\x18\x01 \x03(\v2&.aegis.v1.StatsResponse.UserStatsEntryR\tuserStats\x1aX\n" +
	"\x0eUserStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.aegis.v1.UserTrafficStatsR\x05value:\x028\x01\"\\\n" +
	"\x10UserTrafficStats\x12!\n" +
	"\fupload_bytes\x18\x01 \x01(\x03R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\x02 \x01(\x03R\rdownloadBytes\"\x0f\n" +
	"\rHealthRequest\"\\\n" +
	"\x0eHealthResponse\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x03R\ruptimeSeconds\x12#\n" +
	"\ragent_version\x18\x02 \x01(\tR\fagentVersion2\xfa\x01\n" +
	"\n" +
	"AegisAgent\x128\n" +
	"\x05Apply\x12\x16.aegis.v1.ApplyRequest\x1a\x17.aegis.v1.ApplyResponse\x12;\n" +
	"\x06Status\x12\x17.aegis.v1.StatusRequest\x1a\x18.aegis.v1.StatusResponse\x128\n" +
	"\x05Stats\x12\x16.aegis.v1.StatsRequest\x1a\x17.aegis.v1.StatsResponse\x12;\n" +
	"\x06Health\x12\x17.aegis.v1.HealthRequest\x1a\x18.aegis.v1.HealthResponseBDZBgithub.com/QAdversif/AegisPanel/internal/agentv1pb;aegisv1b\x06proto3"

var (
	file_aegis_v1_agent_proto_rawDescOnce sync.Once
	file_aegis_v1_agent_proto_rawDescData []byte
)

func file_aegis_v1_agent_proto_rawDescGZIP() []byte {
	file_aegis_v1_agent_proto_rawDescOnce.Do(func() {
		file_aegis_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aegis_v1_agent_proto_rawDesc), len(file_aegis_v1_agent_proto_rawDesc)))
	})
	return file_aegis_v1_agent_proto_rawDescData
}

var file_aegis_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aegis_v1_agent_proto_goTypes = []any{
	(*ApplyRequest)(nil),     // 0: aegis.v1.ApplyRequest
	(*ApplyResponse)(nil),    // 1: aegis.v1.ApplyResponse
	(*StatusRequest)(nil),    // 2: aegis.v1.StatusRequest
	(*StatusResponse)(nil),   // 3: aegis.v1.StatusResponse
	(*StatsRequest)(nil),     // 4: aegis.v1.StatsRequest
	(*StatsResponse)(nil),    // 5: aegis.v1.StatsResponse
	(*UserTrafficStats)(nil), // 6: aegis.v1.UserTrafficStats
	(*HealthRequest)(nil),    // 7: aegis.v1.HealthRequest
	(*HealthResponse)(nil),   // 8: aegis.v1.HealthResponse
	nil,                      // 9: aegis.v1.StatsResponse.UserStatsEntry
}
var file_aegis_v1_agent_proto_depIdxs = []int32{
	9, // 0: aegis.v1.StatsResponse.user_stats:type_name -> aegis.v1.StatsResponse.UserStatsEntry
	6, // 1: aegis.v1.StatsResponse.UserStatsEntry.value:type_name -> aegis.v1.UserTrafficStats
	0, // 2: aegis.v1.AegisAgent.Apply:input_type -> aegis.v1.ApplyRequest
	2, // 3: aegis.v1.AegisAgent.Status:input_type -> aegis.v1.StatusRequest
	4, // 4: aegis.v1.AegisAgent.Stats:input_type -> aegis.v1.StatsRequest
	7, // 5: aegis.v1.AegisAgent.Health:input_type -> aegis.v1.HealthRequest
	1, // 6: aegis.v1.AegisAgent.Apply:output_type -> aegis.v1.ApplyResponse
	3, // 7: aegis.v1.AegisAgent.Status:output_type -> aegis.v1.StatusResponse
	5, // 8: aegis.v1.AegisAgent.Stats:output_type -> aegis.v1.StatsResponse
	8, // 9: aegis.v1.AegisAgent.Health:output_type -> aegis.v1.HealthResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_aegis_v1_agent_proto_init() }
func file_aegis_v1_agent_proto_init() {
	if File_aegis_v1_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aegis_v1_agent_proto_rawDesc), len(file_aegis_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aegis_v1_agent_proto_goTypes,
		DependencyIndexes: file_aegis_v1_agent_proto_depIdxs,
		MessageInfos:      file_aegis_v1_agent_proto_msgTypes,
	}.Build()
	File_aegis_v1_agent_proto = out.File
	file_aegis_v1_agent_proto_goTypes = nil
	file_aegis_v1_agent_proto_depIdxs = nil
}
